### PR TITLE
Sewage

### PR DESCRIPTION
**Pull request by anothersimulacrum**
The diff for this branch looks wrong, but when I compare it to CleverRaven/master, it looks correct (though it gives me partial responsibility for the commits). See https://github.com/CleverRaven/Cataclysm-DDA/compare/master...anothersimulacrum:sewage?expand=1

You may want to hard reset to this branch by going `git reset --hard origin pull/2/head:sewage` in the CLI, assuming `origin` is this repo.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Ah, shoot, I realized I made this branch against your master, sorry.

**Comment by chaisawlajatang** [comment]
I wonder maybe it would be better to close that PR and make another branch with all the fixes?

**Comment by anothersimulacrum** [comment]
I've got a clean branch with everything on (mine and petethegoat's) it if you'd like to do that, but I'm not sure how I can give you that branch.
https://github.com/anothersimulacrum/Cataclysm-DDA/tree/sewage

**Comment by chaisawlajatang** [comment]
You can make it from your name, I don't mind. I'm sorry I messed up.

**Comment by anothersimulacrum** [comment]
No, this mess is kinda my fault. I'll do that.

**Comment by anothersimulacrum** [comment]
Okay, done. https://github.com/CleverRaven/Cataclysm-DDA/pull/33339

**Pull request merged**
